// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetCustomerSCardsAPIRequest struct {
	// Unique, hyphen-separated alphanumeric string. We recommend the UUID algorithm, an industry standard that guarantees a high degree of uniqueness length 14 to 36 characters.
	ACorrelationID string `header:"style=simple,explode=false,name=A-Correlation-ID"`
	// Unique Merchant Code provided by Ayoconnect.
	AMerchantCode string `header:"style=simple,explode=false,name=A-Merchant-Code"`
	// Customer phone number used to issue a Card.
	Phone string `pathParam:"style=simple,explode=false,name=phone"`
}

func (o *GetCustomerSCardsAPIRequest) GetACorrelationID() string {
	if o == nil {
		return ""
	}
	return o.ACorrelationID
}

func (o *GetCustomerSCardsAPIRequest) GetAMerchantCode() string {
	if o == nil {
		return ""
	}
	return o.AMerchantCode
}

func (o *GetCustomerSCardsAPIRequest) GetPhone() string {
	if o == nil {
		return ""
	}
	return o.Phone
}

// GetCustomerSCardsAPI200ApplicationJSONCardDetails - Card details
type GetCustomerSCardsAPI200ApplicationJSONCardDetails struct {
	// Available balance on the card
	AvailableBalance *float64 `json:"availableBalance,omitempty"`
	// Unique card ID
	CardID *string `json:"cardID,omitempty"`
	// Initial limit of Card
	CumulativeLimit *float64 `json:"cumulativeLimit,omitempty"`
	// Remaining balance after card is deactivated
	DeactivatedBalance *float64 `json:"deactivatedBalance,omitempty"`
	// Expiry of card in YYMM format
	Expiry *string `json:"expiry,omitempty"`
	// Masked card number
	MaskedCard *string `json:"maskedCard,omitempty"`
	// Status of the card
	Status *string `json:"status,omitempty"`
}

func (o *GetCustomerSCardsAPI200ApplicationJSONCardDetails) GetAvailableBalance() *float64 {
	if o == nil {
		return nil
	}
	return o.AvailableBalance
}

func (o *GetCustomerSCardsAPI200ApplicationJSONCardDetails) GetCardID() *string {
	if o == nil {
		return nil
	}
	return o.CardID
}

func (o *GetCustomerSCardsAPI200ApplicationJSONCardDetails) GetCumulativeLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.CumulativeLimit
}

func (o *GetCustomerSCardsAPI200ApplicationJSONCardDetails) GetDeactivatedBalance() *float64 {
	if o == nil {
		return nil
	}
	return o.DeactivatedBalance
}

func (o *GetCustomerSCardsAPI200ApplicationJSONCardDetails) GetExpiry() *string {
	if o == nil {
		return nil
	}
	return o.Expiry
}

func (o *GetCustomerSCardsAPI200ApplicationJSONCardDetails) GetMaskedCard() *string {
	if o == nil {
		return nil
	}
	return o.MaskedCard
}

func (o *GetCustomerSCardsAPI200ApplicationJSONCardDetails) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetCustomerSCardsAPI200ApplicationJSON - Successful Card Issuance
type GetCustomerSCardsAPI200ApplicationJSON struct {
	// List of cards issued to customer
	CardDetails []GetCustomerSCardsAPI200ApplicationJSONCardDetails `json:"cardDetails,omitempty"`
	// Unique code.
	Code *float64 `json:"code,omitempty"`
	// Unique customer ID
	MerchantCustomerID *string `json:"merchantCustomerID,omitempty"`
	// Description of the response code.
	Message *string `json:"message,omitempty"`
	// Exact TimeStamp of the response in Unix Nanoseconds format.
	ResponseTime *string `json:"responseTime,omitempty"`
}

func (o *GetCustomerSCardsAPI200ApplicationJSON) GetCardDetails() []GetCustomerSCardsAPI200ApplicationJSONCardDetails {
	if o == nil {
		return nil
	}
	return o.CardDetails
}

func (o *GetCustomerSCardsAPI200ApplicationJSON) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetCustomerSCardsAPI200ApplicationJSON) GetMerchantCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantCustomerID
}

func (o *GetCustomerSCardsAPI200ApplicationJSON) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetCustomerSCardsAPI200ApplicationJSON) GetResponseTime() *string {
	if o == nil {
		return nil
	}
	return o.ResponseTime
}

type GetCustomerSCardsAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Card Issuance
	GetCustomerSCardsAPI200ApplicationJSONObject *GetCustomerSCardsAPI200ApplicationJSON
}

func (o *GetCustomerSCardsAPIResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCustomerSCardsAPIResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCustomerSCardsAPIResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetCustomerSCardsAPIResponse) GetGetCustomerSCardsAPI200ApplicationJSONObject() *GetCustomerSCardsAPI200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetCustomerSCardsAPI200ApplicationJSONObject
}
